### ISSUE TITLE
Install plugins link

### ISSUE THREAD

**Issue by emiluzelac** [leac/kamoha_2015#11]
When plugin notice is dismissed, the link, under the appearance still exists.

![screen shot 2015-06-29 at 2 48 46 pm](https://cloud.githubusercontent.com/assets/1784526/8416867/3b934370-1e6e-11e5-9b7d-6f69b6da6641.png)

**Comment by leac** [comment]
Do you mean the Visit site link? Is it supposed to disappear after dismissing the plugin notice? I really wouldn't know how to do that, as the whole plugin recommendation code was taken from [here] (http://tgmpluginactivation.com/) (although the code I took is a little outdated - I have version 2.4.0, and the current version is 2.4.2 - I compared the versions and it doesn't look like there's a difference regarding this issue). What can I do?

**Comment by emiluzelac** [comment]
Once you install the plugins, does the menu item "Install Plugins" goes disappear? It didn't for me :( Not really sure how to remove if it doesn't you may want to try: https://github.com/TGMPA/TGM-Plugin-Activation Gary is very helpful.

**Comment by leac** [comment]
Doesn't happen on any of my machines.
