### ISSUE TITLE
Security: $_SERVER

### ISSUE THREAD

**Issue by emiluzelac** [leac/kamoha_2015#14]
[../helpers.php](https://github.com/leac/kamoha_2015/blob/master/inc/helpers.php#L1068)
[../jewish-calendar.php](https://github.com/leac/kamoha_2015/blob/master/inc/jewish-calendar.php#L48)
****
`$_SERVER` variable alone is never safe or secure and `HTTP_X_REQUESTED_WITH` are not reliable. 

This [issue](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/72) will give you more details how to make them more secure.

**Comment by leac** [comment]
Could you recommend am alternative to `HTTP_X_REQUESTED_WITH`? I tried Googling, but couldn't find a good solution.

**Comment by emiluzelac** [comment]
The main issue with `HTTP_X_REQUESTED_WITH` is server support, if your theme is used on one site and it works you're good to go.
