### ISSUE TITLE
Home post ID

### ISSUE THREAD

**Issue by justintadlock** [leac/kamoha_2015#16]
I noticed your note here:

	<article  <?php post_class( $article_class ); ?>>

If you're loading the same post twice on the home page, that's a sign that something's broken.  The ID really should be there.

**Comment by leac** [comment]
I can see your point. However, in our homepage we also have a plugin that show most popular posts. Sometimes one of those popular posts is still on the homepage.
What can I do in this case?

**Comment by leac** [comment]
Client wants the 2 posts that are hidden by "load more" button to appear under their category on the homepage as well.
The best thing would be to track how many users actually click the "load more" button, and decide if it's necessary or not. 
Till we implement that, the id stays out
