### ISSUE TITLE
Hardcoded item: Styles

### ISSUE THREAD

**Issue by emiluzelac** [leac/kamoha_2015#2]
[../header.php](https://github.com/leac/kamoha_2015/blob/master/header.php)
****

We want to avoid hardcoding styles:

```
        <link href='http://fonts.googleapis.com/css?family=Alef:400,700&subset=latin,hebrew' rel='stylesheet' type='text/css'>
        <style type="text/css">
            @font-face {font-family: 'icomoon';src:url('<?php echo get_stylesheet_directory_uri(); ?>/fonts/icomoon.eot?-416wh5');src:url('<?php echo get_stylesheet_directory_uri(); ?>/fonts/icomoon.eot?#iefix-416wh5') format('embedded-opentype'),url('<?php echo get_stylesheet_directory_uri(); ?>/fonts/icomoon.woff?-416wh5') format('woff'),url('<?php echo get_stylesheet_directory_uri(); ?>/fonts/icomoon.ttf?-416wh5') format('truetype'),url('<?php echo get_stylesheet_directory_uri(); ?>/fonts/icomoon.svg?-416wh5#icomoon') format('svg');font-weight: normal;font-style: normal;}
        </style>
```

and `wp_enqueue_style` them from functions file instead.

Here's an [example](http://themeshaper.com/2014/08/13/how-to-add-google-fonts-to-wordpress-themes/) how to add Google fonts and also one for [inline styles](https://codex.wordpress.org/Function_Reference/wp_add_inline_style).

**Comment by justintadlock** [comment]
Also, make sure to either use `https:` or leave off the `http:` or `https:` off entirely.

**Comment by leac** [comment]
Thanks.
I managed to add it to the frontend, but not to the editor, event though I followed the method from the article you linked to. What could the problem be?

**Comment by emiluzelac** [comment]
Awesome! For the editor, please see: https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyfourteen/functions.php#L71
