### ISSUE TITLE
Textdomain should match theme slug

### ISSUE THREAD

**Issue by justintadlock** [leac/kamoha_2015#20]
The theme textdomain should match the theme slug.  Currently, the textdomain is `kamoha` but the slug is `kamoha_2015`.  These should be the same because some translation system (like the WP i18n dev tool) will expect them to match.

**Comment by leac** [comment]
Fixed by 204247348191936cf28d38b35c45c614c9779d4d and bc0f62cb56764f8187e53a00d1c2bb35720d178a
