### ISSUE TITLE
Design: Inconsistent headers

### ISSUE THREAD

**Issue by justintadlock** [leac/kamoha_2015#23]
There should be some consistency in how headers are done.  Make sure there's a clear, visual hierarchy as well.

![headers](https://cloud.githubusercontent.com/assets/1816309/8438796/bb421712-1f2d-11e5-8981-ef2b622e955a.png)

**Comment by leac** [comment]
All headers are bold now, and have a consistent decrease in font-size. The only anomaly is that header 3 is blue, and we want it that way/
![image](https://cloud.githubusercontent.com/assets/1826720/21602892/7e20fd58-d1a1-11e6-80ce-ea5320f469eb.png)
