### ISSUE TITLE
License / Copyright

### ISSUE THREAD

**Issue by justintadlock** [leac/kamoha_2015#28]
Make sure to list all the licenses and copyrights for all third-party code and/or resources used in the theme in the `readme`, `license`, or `copying` file.

**Comment by leac** [comment]
For example:

Google Webfonts: Open Sans. which are under Apache License, Version 2.0

Copyrights for Images used in this theme GPL3.
The Following images present in the 'images/' folder:
	serach-button1.jpg
	screenshot.png

**Comment by leac** [comment]
closed by b25a71f43188eadb7a84fec702ab7398fa6a1741
