### ISSUE TITLE
Unused items: Fonts

### ISSUE THREAD

**Issue by emiluzelac** [leac/kamoha_2015#3]
Since theme is loading fonts from Google directly you no longer need the following and it can be removed:

[../style.css/](https://github.com/leac/kamoha_2015/blob/master/style.css#L47-58)
```
/* @font-face {
   font-family: 'Alef';
   src: url('fonts/Alef-Regular.eot');
   src: url('fonts/Alef-Regular.eot?#iefix') format('embedded-opentype'),
       url('fonts/Alef-Regular.woff') format('woff'),
       url('fonts/Alef-Regular.ttf') format('truetype'),
       url('fonts/Alef-Regular.svg#alefregular') format('svg');
   font-weight: normal;
   font-style: normal;
} */
```
and the actual font from the [/fonts/](https://github.com/leac/kamoha_2015/tree/master/fonts) folder.

**Comment by leac** [comment]
Fixed with commit d80472f1b85c0f4d304e6a2bf98f471c4986b6b5
