### ISSUE TITLE
Hardcoded item: Favicon

### ISSUE THREAD

**Issue by emiluzelac** [leac/kamoha_2015#4]
[../header.php](https://github.com/leac/kamoha_2015/blob/master/header.php#L18)
****
When adding a favicon, we want to make sure that it is not hardcoded. If theme includes one, please turn it off by default.

Very soon core will have this ability too: [https://core.trac.wordpress.org/ticket/16434](16434).

**Comment by leac** [comment]
How can I not hard code it, and how can I turn it off? Do I do it the same way I added the Google fonts, according to the article you linked to?

**Comment by emiluzelac** [comment]
Take a look at: https://github.com/devinsays/platform/blob/master/inc/customizer-options.php#L40-47 please.
