### ISSUE TITLE
Footer menu 

### ISSUE THREAD

**Issue by emiluzelac** [leac/kamoha_2015#6]
[../footer.php](https://github.com/leac/kamoha_2015/blob/master/footer.php)
****
I don't fully understand how footer menu links function, but I am pretty sure that we can do this differently and dynamically.

```
       <a href="<?php echo get_permalink( LINKS_AND_EMERGECY ) ?>"><?php echo get_the_title( LINKS_AND_EMERGECY ) ?></a>
        <span class="sep"> | </span>
        <a href="http://wordpress.org/"><?php printf( __( 'Proudly powered by %s', 'kamoha' ), 'WordPress' ); ?></a><!--  rel="generator" -->
        <span class="sep"> | </span>
        <a href="<?php echo get_permalink( ABOUT_PAGE ) . '#credits'; ?>"><?php _e( 'credits', 'kamoha' ) ?></a>
        <?php if ( is_user_logged_in() ) { ?>
            <span class="sep"> | </span>
            <a href="<?php echo get_permalink( DOCUMENTATION_PAGE ) ?>"><?php echo get_the_title( DOCUMENTATION_PAGE ) ?></a>
            <span class="sep"> | </span>
            <a href="<?php echo get_category_link( MEETINGS_CAT ) . '&futureposts=1' ?>"><?php echo get_cat_name( MEETINGS_CAT ) . ' ' . __( 'future', 'kamoha' ) ?></a>
        <?php } ?>
```

The most easiest way is to create a custom menu with a footer area location. With custom menus you can add any link you need. Just like you added one [here](https://github.com/leac/kamoha_2015/blob/master/functions.php#L47).

**Comment by leac** [comment]
I agree. I'm just wondering: some of the menu items are only shown to logged in users. Should I create 2 menus, one for all users, and one for logged in users?

**Comment by emiluzelac** [comment]
You can definitely do that :)
